import { Layout } from '../components/Layout'
import Head from 'next/head'
import { client } from '/sanity/lib/client'

import Image from 'next/image'
import { AnimatedText } from '../components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '../components/Icons'
import { HireMe } from '../components/HireMe'
import { TransitionEffect } from '../components/TransitionEffect'
export default function Home({ data }) {
  const { body, footer, navbare } = data;

  return (
    <>
      <Head>
        <title>Hamza Rahmoun | Home</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8 '>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={body.profilePicture}
                alt='CodeBucks' className='w-full h-auto g:w-full md:inline-block md:w-full'
                priority
                width={500}
                height={500}
                sizes='(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw
              '
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText 
              text={body.homeheadline} 
              className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl pb-8
              
              '/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
              {body.homeparagraph}              </p>
              <div className='flex items-center self-start mt-2 lg:self-center '>
                <Link href={body.resume} target="_blank"
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark

                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                md:p-2 md:px-4 md:text-base
                '
                  download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} /></Link>
                <Link href={`mailto:${body.contactEmail}`} target="_blank"
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light
                md:text-base
                  
                
                '
                > Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe body={body}/>
      </main>
      
    </>
  )
}

export async function getStaticProps() {
  // Fetch data from Sanity using GROQ query
  const data = await client.fetch(`
    *[_type == "home"][0]{
      body
      {
        "profilePicture": profilePicture.asset->url,
        "resume":resume.asset->url,
        homeheadline,
        homeparagraph,
        contactEmail

      },
      footer,
      navbare
    }
  `);

  return {
    props: {
      data,
    },
  };
}

